In [43]:
from sklearn import datasets
train = datasets.load_files("BBC", encoding="latin1")

In [95]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit_transform(train.data)

<2225x29421 sparse matrix of type '<class 'numpy.int64'>'
	with 449254 stored elements in Compressed Sparse Row format>

In [84]:
from sklearn import model_selection
training, testing = model_selection.train_test_split(train.data, train_size=0.8, test_size=0.2, random_state=None)

In [97]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB()),
])
vectorizer.fit_transform(training)
text_clf.fit(training, train.target)

ValueError: Found input variables with inconsistent numbers of samples: [1780, 2225]

In [90]:
import numpy as np
predicted = text_clf.predict(testing)
np.mean(predicted == train.target)

C:\Users\Julie\AppData\Local\Temp/ipykernel_23196/982489410.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.mean(predicted == train.target)


0.0

In [67]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(train.target, predicted))

[[504   0   3   0   3]
 [  5 361  10   5   5]
 [  2   0 413   0   2]
 [  1   0   0 510   0]
 [  2   2   0   1 396]]


In [66]:
from sklearn.metrics import classification_report
target_names = ['business', 'entertainment', 'politics', 'sports', 'tech']
print(classification_report(train.target, predicted, target_names=target_names))

               precision    recall  f1-score   support

     business       0.98      0.99      0.98       510
entertainment       0.99      0.94      0.96       386
     politics       0.97      0.99      0.98       417
       sports       0.99      1.00      0.99       511
         tech       0.98      0.99      0.98       401

     accuracy                           0.98      2225
    macro avg       0.98      0.98      0.98      2225
 weighted avg       0.98      0.98      0.98      2225



In [68]:
from sklearn.metrics import accuracy_score
print(accuracy_score(train.target, predicted))

0.9815730337078652
